services:
  nginx:
    ports: ["80:80"]

  api-gateway:
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M

  todo-service:
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M

  auth-service:
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: 384M

  file-service:
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: 384M

  notification-service:
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: 384M

  audit-service:
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M

  search-service:
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: 384M
